CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT,
    first_name TEXT,
    last_name Text, 
    password TEXT NOT NULL UNIQUE,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    profile_image TEXT,
    phone_number TEXT,
    user_type TEXT NOT NULL
);