CREATE TABLE team_members (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    profile_image TEXT,
    phone_number TEXT

);