CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    location TEXT, 
    date DATE NOT NULL,
    time_start TIME NOT NULL, 
    time_end TIME NOT NULL,
    title TEXT NOT NULL,
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE
);